const providerData = [
  {
    name: "Catherine Jones",
    subtitle1: "Group Practise",
    subtitle2: "(773)123-4567",
    facilityName: "Northwestern Hospital",
    facilityAddress: "Northwestern Hospital, Address Long",
    distance: "0.6miles",
    smartCompare: true,
    speciality: "Orthopadeic Surgery",
    subSpeciality: "Knee Surgery",
  },
  
  {
    name: "Amy Chen",
    subtitle1: "Group Practice",
    subtitle2: "(773)567-8901",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Long",
    distance: "3.2 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Foot and Ankle Surgery",
  },

  {
    name: "John Lee",
    subtitle1: "Group Practice",
    subtitle2: "(773)987-6543",
    facilityName: "Northwestern Hospital",
    facilityAddress: "Northwestern Hospital, Address Short",
    distance: "1.2 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hip Surgery",
  },

  {
    name: "Emily Wang",
    subtitle1: "Private Practice",
    subtitle2: "(773)234-5678",
    facilityName: "Northwestern Hospital",
    facilityAddress: "Northwestern Hospital, Address Long",
    distance: "0.8 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Shoulder Surgery",
  },

  {
    name: "Alex Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)345-6789",
    facilityName: "Northwestern Hospital",
    facilityAddress: "Northwestern Hospital, Address Short",
    distance: "1.5 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand Surgery",
  },

  {
    name: "Roy Que",
    subtitle1: "Private Practice",
    subtitle2: "(773)456-7890",
    facilityName: "Northwestern Hospital",
    facilityAddress: "Northwestern Hospital, Address Long",
    distance: "0.6 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Knee Surgery",
  },


  {
    name: "Grace Park",
    subtitle1: "Group Practice",
    subtitle2: "(773)678-9012",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Short",
    distance: "2.7 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Spine Surgery",
  },

  {
    name: "Hannah Lee",
    subtitle1: "Private Practice",
    subtitle2: "(773)789-0123",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Long",
    distance: "2.5 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand and Wrist Surgery",
  },

  {
    name: "Roy Que",
    subtitle1: "Group Practice",
    subtitle2: "(773)890-1234",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Short",
    distance: "3.5 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hip and Knee Replacement",
  },
  {
    name: "Ethan Kim",
    subtitle1: "Private Practice",
    subtitle2: "(773)012-3456",
    facilityName: "Advocate Illinois Masonic Medical Center",
    facilityAddress: "Advocate Illinois Masonic Medical Center, Address Long",
    distance: "4.8 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand and Upper Extremity Surgery",
  },

  {
    name: "Daniel Lee",
    subtitle1: "Group Practice",
    subtitle2: "(773)123-4567",
    facilityName: "Advocate Illinois Masonic Medical Center",
    facilityAddress: "Advocate Illinois Masonic Medical Center, Address Short",
    distance: "5.1 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Sports Medicine",
  },

  {
    name: "Samantha Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)234-5678",
    facilityName: "Advocate Illinois Masonic Medical Center",
    facilityAddress: "Advocate Illinois Masonic Medical Center, Address Long",
    distance: "4.3 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Pediatric Orthopedics",
  },

  {
    name: "Roy Que",
    subtitle1: "Private Practice",
    subtitle2: "(773)345-6789",
    facilityName: "Advocate Illinois Masonic Medical Center",
    facilityAddress: "Advocate Illinois Masonic Medical Center, Address Short",
    distance: "4.9 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand Surgery",
  },

  {
    name: "David Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)456-7890",
    facilityName: "University of Chicago Medicine",
    facilityAddress: "University of Chicago Medicine, Address Long",
    distance: "8.2 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Joint Replacement",
  },

  {
    name: "Jenny Lee",
    subtitle1: "Group Practice",
    subtitle2: "(773)567-8901",
    facilityName: "University of Chicago Medicine",
    facilityAddress: "University of Chicago Medicine, Address Short",
    distance: "7.6 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Spine Surgery",
  },

  {
    name: "Roy Que",
    subtitle1: "Private Practice",
    subtitle2: "(773)678-9012",
    facilityName: "University of Chicago Medicine",
    facilityAddress: "University of Chicago Medicine, Address Long",
    distance: "8.8 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand and Upper Extremity Surgery",
  },

  {
    name: "Michelle Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)789-0123",
    facilityName: "University of Chicago Medicine",
    facilityAddress: "University of Chicago Medicine, Address Short",
    distance: "7.9 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Foot and Ankle Surgery",
  },
  {
    name: "Sarah Kim",
    subtitle1: "Private Practice",
    subtitle2: "(773)890-1234",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Long",
    distance: "2.1 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand and Upper Extremity Surgery",
  },

  {
    name: "Matthew Lee",
    subtitle1: "Group Practice",
    subtitle2: "(773)901-2345",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Short",
    distance: "1.8 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Sports Medicine",
  },

  {
    name: "Roy Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)012-3456",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Long",
    distance: "2.2 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Pediatric Orthopedics",
  },

  {
    name: "Andrew Lee",
    subtitle1: "Private Practice",
    subtitle2: "(773)123-4567",
    facilityName: "Rush University Medical Center",
    facilityAddress: "Rush University Medical Center, Address Short",
    distance: "1.9 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand Surgery",
  },

  {
    name: "Jennifer Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)234-5678",
    facilityName: "NorthShore University HealthSystem",
    facilityAddress: "NorthShore University HealthSystem, Address Long",
    distance: "14.6 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Joint Replacement",
  },

  {
    name: "Ryan Que",
    subtitle1: "Group Practice",
    subtitle2: "(773)345-6789",
    facilityName: "NorthShore University HealthSystem",
    facilityAddress: "NorthShore University HealthSystem, Address Short",
    distance: "13.9 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Spine Surgery",
  },

  {
    name: "David Lee",
    subtitle1: "Private Practice",
    subtitle2: "(773)456-7890",
    facilityName: "NorthShore University HealthSystem",
    facilityAddress: "NorthShore University HealthSystem, Address Long",
    distance: "15.5 miles",
    smartCompare: true,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Hand and Upper Extremity Surgery",
  },

  {
    name: "Rachel Kim",
    subtitle1: "Group Practice",
    subtitle2: "(773)567-8901",
    facilityName: "NorthShore University HealthSystem",
    facilityAddress: "NorthShore University HealthSystem, Address Short",
    distance: "14.1 miles",
    smartCompare: false,
    speciality: "Orthopedic Surgery",
    subSpeciality: "Foot and Ankle Surgery",
  },
];

function getMockData(page: number) {
  let x = (page-1) * 8;
  const data = [
    providerData[x],
    providerData[x + 1],
    providerData[x + 2],
    providerData[x + 3],
    providerData[x + 4],
    providerData[x + 5],
    providerData[x + 6],
    providerData[x + 7],
  ];
  return data;
}

export { providerData, getMockData };
